# config.yaml

scoring_system: th1000
scoring_mode: place_based # place_based , round_based , mixed
current_year: 2025
top_n: 100
# allowed_years: [2017, 2018, 2019, 2021, 2022, 2023, 2024]
allowed_years: [2021, 2022, 2023, 2024]

input_paths:
  # - "data/rfs/surfing/shortboard/shortboard_men_*.csv"

output:
  # filename: output/rankings/surfing/shortboard_men.csv
  translate_columns: false
  columns:
    - Rank
    - Name
    - Sport Rank
    - Birth Year
    - Region
    - Category
    - YearScores
    - Total Points

anonymization:
  enabled: false

sorting:
  enabled: true

bonuses:
  decay:
    enabled: false
    factor: 0.8

  participant_factor:
    enabled: false
    rules:
      - min: 1
        max: 5
        factor: 0.5
      - min: 6
        max: 8
        factor: 0.75
      - min: 9
        max: "inf"
        factor: 1.0

  sport_rank:
    enabled: false
    values:
      МС: 80
      КМС: 50
      "1 разряд": 30
      "2 разряд": 20
      "3 разряд": 10
      "": 0

  participation:
    enabled: false
    points: 50

wildcard:
  ranking_file: output/rankings/rfs/rus/shortboard/ranking_men.json
  output_file: output/wildcard/shortboard_men.json

  top_n: 64               # Максимальный рейтинг для отбора
  min_participations: 1   # Минимальное количество участий
  last_years_period: 4    # За последние N лет
  max_best_place: 1
  min_best_place: 4

  # ranking_file: output/rankings/rfs/rus/shortboard/ranking_women.json
  # output_file: output/wildcard/shortboard_women.json

  # ranking_file: output/rankings/rfs/rus/longboard/ranking_men.json
  # output_file: output/wildcard/longboard_men.json

  # ranking_file: output/rankings/rfs/rus/longboard/ranking_women.json
  # output_file: output/wildcard/longboard_women.json

trends:
  # input_ranking_file: output/rankings/surfing/shortboard_women.csv
  # output_general_file: output/trends/general_shortboard_men_stats.csv
  # output_detailed_file: output/trends/detailed_shortboard_men_stats.csv

  # input_ranking_file: output/rankings/surfing/longboard_men.csv
  # output_general_file: output/trends/general_longboard_men_stats.csv
  # output_detailed_file: output/trends/detailed_longboard_men_stats.csv

  input_ranking_file: output/rankings/rfs/rus/shortboard/women.csv
  output_general_file: output/trends/general_shortboard_women_stats.csv
  output_detailed_file: output/trends/detailed_shortboard_women_stats.csv

  # input_ranking_file: output/rankings/surfing/shortboard_women.csv
  # output_general_file: output/trends/general_shortboard_women_stats.csv
  # output_detailed_file: output/trends/detailed_shortboard_women_stats.csv
