# config.yaml

scoring_system: wsl_csh
current_year: 2025
top_n: 100
allowed_years: [2025]

input_paths: []

output:
  # filename: output/rankings/surfing/shortboard_men.csv
  translate_columns: false
  columns:
    - Rank
    - Name
    - Sport Rank
    - Birth Year
    - Region
    - Category
    - YearScores
    - Total Points

anonymization:
  enabled: false

sorting:
  enabled: true

bonuses:
  decay:
    enabled: false
    factor: 0.8

  participant_factor:
    enabled: false
    rules:
      - min: 1
        max: 5
        factor: 0.5
      - min: 6
        max: 8
        factor: 0.75
      - min: 9
        max: "inf"
        factor: 1.0

  rank:
    enabled: false
    values:
      МС: 80
      КМС: 50
      "1 разряд": 30
      "2 разряд": 20
      "3 разряд": 10
      "": 0

  participation:
    enabled: false
    points: 50

wildcard:
  top_n: 16
  min_participations: 2
  last_years_period: 3
  min_best_place: 3

  ranking_file: output/rankings/surfing/shortboard_men.csv
  output_file: output/wildcard/shortboard_men.csv

trends:
  input_ranking_file: output/rankings/surfing/shortboard_men.csv
  output_general_file: output/trends/general_shortboard_men_stats.csv
  output_detailed_file: output/trends/detailed_shortboard_men_stats.csv
